# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.0
_src_path: gh:quickplates/nixos
accountname: spietras
description: NixOS configs for my homelab ❄️
docs: false
projectname: systems
reponame: systems
repourl: https://github.com/spietras/systems
